In [2]:
import numpy as np
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + 10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [6]:
arr*arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
arr_2d = arr.reshape(3,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr_2d**3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

In [12]:
arr_1d = np.array([1,2,3])
arr_2d * arr_1d

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [13]:
arr_2d/arr_2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [16]:
np.sin(arr_2d)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [17]:
np.log(arr_2d)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [18]:
np.insert(arr,5,10)

array([ 1,  2,  3,  4,  5, 10,  6,  7,  8,  9])

In [19]:
np.delete(arr,7)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [20]:
np.append(arr,120)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 120])

In [23]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [30]:
np.concatenate((a,b), axis = None)

array([1, 2, 3, 4, 5, 6])

In [32]:
np.where(arr>5,90,arr)

array([ 1,  2,  3,  4,  5, 90, 90, 90, 90])

In [36]:
np.where(arr>5,1,2)

array([2, 2, 2, 2, 2, 1, 1, 1, 1])

In [37]:
np.where(arr_2d <= 5,0,arr_2d)

array([[0, 0, 0],
       [0, 0, 6],
       [7, 8, 9]])